<a href="https://colab.research.google.com/github/saparbayev-azizbek-12/bi-and-ai-talents-dl/blob/main/lesson-8/lesson_8_Dropuot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
class CustomDropout:
  def __init__(self, p=0.2):
    self.p = p
    self.training = True

  def train(self):
    self.training = True

  def eval(self):
    self.training = False

  def __call__(self, x):
    if not self.training:
      return
    mask = (torch.rand_like(x) > self.p).float()
    return mask

In [3]:
x = torch.full((10,), 5.)
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
x_like = torch.rand_like(x) > 0.2
x_like

tensor([ True,  True,  True,  True, False, False, False,  True,  True,  True])

In [44]:
cd = CustomDropout(0.3)
cd.training = True

In [45]:
cd.training

True

In [46]:
cd(x)

tensor([0., 1., 0., 1., 0., 1., 1., 0., 1., 0.])

In [47]:
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])