<a href="https://colab.research.google.com/github/saparbayev-azizbek-12/bi-and-ai-talents-dl/blob/main/lesson-28/SelfAttention_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your (x^1)
    [0.55, 0.87, 0.66], # journey (x^2)
    [0.57, 0.85, 0.64], # starts (x^3)
    [0.22, 0.58, 0.33], # with (x^4)
    [0.77, 0.25, 0.10], # one (x^5)
])

In [ ]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
attn_scores = inputs @ inputs.T

attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)
attn_weights_2_naive = softmax_naive(attn_scores_2)

context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2_naive[i]*x_i

all_context_vecs = attn_weights_2_naive @ inputs

In [ ]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070])


In [ ]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1743, 0.2730, 0.2695, 0.1540, 0.1291])
Sum: tensor(1.)


In [ ]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)
attn_weights_2_naive = softmax_naive(attn_scores_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1646, 0.2826, 0.2771, 0.1473, 0.1285])
Sum: tensor(1.)


In [ ]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1646, 0.2826, 0.2771, 0.1473, 0.1285])
Sum: tensor(1.)


In [ ]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i
print(context_vec_2)

tensor([0.5155, 0.6236, 0.5717])


In [ ]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[9.9950e-01, 9.5440e-01, 9.4220e-01, 4.7530e-01, 4.5760e-01, 5.4074e+22],
        [9.5440e-01, 1.4950e+00, 1.4754e+00, 8.4340e-01, 7.0700e-01, 1.4580e-19],
        [9.4220e-01, 1.4754e+00, 1.4570e+00, 8.2960e-01, 7.1540e-01, 2.8404e+29],
        [4.7530e-01, 8.4340e-01, 8.2960e-01, 4.9370e-01, 3.4740e-01, 2.7491e+20],
        [4.5760e-01, 7.0700e-01, 7.1540e-01, 3.4740e-01, 6.6540e-01, 3.3245e+21],
        [6.7494e-07, 8.2356e-10, 1.0812e-05, 1.0616e+21, 6.6713e-10, 8.5078e-07]])


In [ ]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654]])


In [ ]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2455, 0.2346, 0.2318, 0.1453, 0.1428],
        [0.1646, 0.2826, 0.2771, 0.1473, 0.1285],
        [0.1648, 0.2809, 0.2757, 0.1472, 0.1314],
        [0.1733, 0.2505, 0.2471, 0.1766, 0.1525],
        [0.1753, 0.2250, 0.2269, 0.1570, 0.2158]])


In [ ]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.5086, 0.5580, 0.5839],
        [0.5155, 0.6236, 0.5717],
        [0.5160, 0.6217, 0.5702],
        [0.5094, 0.5945, 0.5512],
        [0.5292, 0.5599, 0.5231]])


In [ ]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [ ]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [ ]:
torch.manual_seed(789)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.8014, 0.9434],
        [0.8285, 0.9923],
        [0.8283, 0.9920],
        [0.8003, 0.9382],
        [0.8076, 0.9539]], grad_fn=<MmBackward0>)


In [ ]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec

In [ ]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.0500,  0.1114],
        [-0.0516,  0.1093],
        [-0.0516,  0.1093],
        [-0.0514,  0.1098],
        [-0.0514,  0.1098]], grad_fn=<MmBackward0>)


In [ ]:
import torch

inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your (x^1)
    [0.55, 0.87, 0.66], # journey (x^2)
    [0.57, 0.85, 0.64], # starts (x^3)
    [0.22, 0.58, 0.33], # with (x^4)
    [0.77, 0.25, 0.10], # one (x^5)
])

In [ ]:
import torch
from torch import nn

class SelfAttention_v3(nn.Module):
    def __init__(self, d_in, d_out, bias=False):
        super().__init__()
        self.w_key = nn.Linear(d_in, d_out, bias=bias)
        self.w_query = nn.Linear(d_in, d_out, bias=bias)
        self.w_value = nn.Linear(d_in, d_out, bias=bias)

    def forward(self, x):
        key = self.w_key(x)     # shape [n, d_out]
        query = self.w_query(x) # shape [n, d_out]
        value = self.w_value(x) # shape [n, d_out]

        att_scores = query @ key.T
        att_weights = torch.softmax(att_scores / key.size(-1)**0.5, dim=1)
        context_vector = att_weights @ value
        return context_vector

In [ ]:
x = torch.randn(10,4)

In [ ]:
a = SelfAttention_v3(4,6)
a(x)

tensor([[ 0.0905,  0.0647, -0.0638, -0.0029,  0.0424,  0.0355],
        [ 0.1314,  0.1226, -0.0575,  0.0792,  0.0491, -0.0552],
        [ 0.1397,  0.0938, -0.0670,  0.0321,  0.0747,  0.0045],
        [ 0.0581,  0.0113, -0.0472, -0.0133,  0.0671,  0.0392],
        [ 0.0433,  0.0283, -0.0384,  0.0511,  0.0633, -0.0410],
        [ 0.1215,  0.2133, -0.0533,  0.0916, -0.0837, -0.0773],
        [ 0.0383, -0.0122, -0.0396,  0.0460,  0.1132, -0.0337],
        [ 0.0835,  0.0414, -0.0552,  0.0175,  0.0752,  0.0095],
        [ 0.0216, -0.0455, -0.0385,  0.0116,  0.1208,  0.0038],
        [ 0.0541, -0.1787, -0.0888, -0.1079,  0.3007,  0.1681]],
       grad_fn=<MmBackward0>)

Multi head attention

In [15]:
class CausalAttention_v1(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout_p, bias=False):
        super().__init__()
        self.w_key = nn.Linear(d_in, d_out, bias=bias)
        self.w_query = nn.Linear(d_in, d_out, bias=bias)
        self.w_value = nn.Linear(d_in, d_out, bias=bias)
        self.dropout = nn.Dropout(dropout_p)
        self.register_buffer(
            "mask",
            torch.triu(context_length, context_length, diagonal=1)
        )


    def forward(self, x):
        T = x.size(-2)
        key = self.w_key(x)
        query = self.w_query(x)
        value = self.w_value(x)

        att_scores = query @ key.transpose(-1, -2)
        att_scores.masked_fill_(
            self.mask.bool()[:T, T:], -torch.inf
        )
        att_weights = torch.softmax(att_scores / key.size(-1)**0.5, dim=1)
        att_weights = self.dropout(att_weights)
        context_vector = att_weights @ value
        return context_vector

In [16]:
class MultiHeadAttention_v1(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout_p, num_heads):
        self.heads = nn.ModuleList(
            [
                CausalAttention_v1(d_in, d_out, context_length, dropout_p)
                for _ in range(num_heads)
            ]
        )

    def forward(self):
        torch.cat([head(x) for head in self.heads], dim=-1)

In [40]:
class MultiHeadAttention_v2(nn.Module):
    def __init__(self, d_modul, num_heads, dropout, context_length, qkv_bias=False):
        super().__init__()
        if d_modul % num_heads != 0:
            raise "d_modul must be divisable num_heads"
        self.d_modul = d_modul
        self.num_heads = num_heads
        self.head_dim = d_modul // num_heads
        self.W_key = nn.Linear(d_modul, d_modul, bias=qkv_bias)
        self.W_value = nn.Linear(d_modul, d_modul, bias=qkv_bias)
        self.W_query = nn.Linear(d_modul, d_modul, bias=qkv_bias)
        self.register_buffer(
            "mask",
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )
        self.output = nn.Linear(d_modul, d_modul)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x shape: [B, T, d_modul]
        B, T, d_modul = x.shape
        keys = self.W_key(x).view(B, T, self.num_heads, self.head_dim) # shape: [B, T, 4, 196]
        values = self.W_value(x).view(B, T, self.num_heads, self.head_dim)
        queries = self.W_query(x).view(B, T, self.num_heads, self.head_dim)

        keys = keys.transpose(1, 2) # shape: [B, 4, T, 196]
        values = values.transpose(1, 2)
        queries = queries.transpose(1, 2)

        att_scores = queries @ keys.transpose(-1, -2)
        mask_bool = self.mask.bool()[:T, :T]
        att_scores.masked_fill_(mask_bool, -torch.inf)
        att_weights = torch.softmax(
            att_scores / keys.size(-1)**0.5, dim=-1
        )
        att_weights = self.dropout(att_weights)
        context_vec = (att_weights @ values).transpose(1, 2)
        context_vec = context_vec.contiguous().view(B, T, self.d_modul)
        context_vec = self.output(context_vec)

        return context_vec


In [27]:
x = torch.randn(4, 10, 784)

In [41]:
d_modul = 784
num_heads = 4
dropout = 0.3
context_length = 10

model = MultiHeadAttention_v2(d_modul, num_heads, dropout, context_length)
out = model.forward(x)

In [42]:
out.shape

torch.Size([4, 10, 784])